server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://dpg-d6kg8vfafjfc73edc1b0-a.oregon-postgres.render.com/sprintboard
spring.datasource.username=sprintboard_user
spring.datasource.password=sprintboard_user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
